In [1]:
import numpy as np
import Raw_data_receiver as rdr
import Create_window_index as windower

In [2]:
data_receiver = rdr.rawdatareceiver()

In [3]:
rawdata = data_receiver.receive_data_file("chart_data/eur_usd_daily.csv", "eurusd_daily")
# 0 2 3 4 1
rawdata = rawdata.iloc[::-1].reset_index()

read file with header as follows 

         Date   Price    Open    High     Low  Vol. Change %
0  03/27/2017  1.0865  1.0797  1.0905  1.0795   NaN    0.61%
1  03/24/2017  1.0799  1.0784  1.0820  1.0761   NaN    0.15%
2  03/23/2017  1.0783  1.0797  1.0807  1.0769   NaN   -0.13%
3  03/22/2017  1.0797  1.0810  1.0827  1.0776   NaN   -0.13%
4  03/21/2017  1.0811  1.0740  1.0822  1.0720   NaN    0.67%




In [5]:
rawdata

index        date    open    high     low   close
0      4999  01/26/1998  1.1090  1.1196  1.0963  1.0991
1      4998  01/27/1998  1.0991  1.1055  1.0985  1.1022
2      4997  01/28/1998  1.1021  1.1021  1.0877  1.0878
3      4996  01/29/1998  1.0870  1.0927  1.0785  1.0799
4      4995  01/30/1998  1.0792  1.0865  1.0771  1.0790
...     ...         ...     ...     ...     ...     ...
4995      4  03/21/2017  1.0740  1.0822  1.0720  1.0811
4996      3  03/22/2017  1.0810  1.0827  1.0776  1.0797
4997      2  03/23/2017  1.0797  1.0807  1.0769  1.0783
4998      1  03/24/2017  1.0784  1.0820  1.0761  1.0799
4999      0  03/27/2017  1.0797  1.0905  1.0795  1.0865

[5000 rows x 6 columns]

In [2]:
print(windower.create_window_indexes(10,5))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [6]:
import Create_labels as cl

In [7]:
labels = cl.multi_distance_labele_creator(rawdata,0.01,0.5,4)