In [1]:
import numpy as np
import pandas as pd
import Raw_data_receiver as rdr
import Create_window_index as windower

In [2]:
data_receiver = rdr.rawdatareceiver()

In [3]:
rawdata = data_receiver.receive_data_file("chart_data/eur_usd_daily.csv", "eurusd_daily")
# 0 2 3 4 1
rawdata = rawdata.iloc[::-1]
rawdata.index = np.arange(0,len(rawdata))[::-1]

read file with header as follows 

         Date   Price    Open    High     Low  Vol. Change %
0  03/27/2017  1.0865  1.0797  1.0905  1.0795   NaN    0.61%
1  03/24/2017  1.0799  1.0784  1.0820  1.0761   NaN    0.15%
2  03/23/2017  1.0783  1.0797  1.0807  1.0769   NaN   -0.13%
3  03/22/2017  1.0797  1.0810  1.0827  1.0776   NaN   -0.13%
4  03/21/2017  1.0811  1.0740  1.0822  1.0720   NaN    0.67%




In [4]:
rawdata

date    open    high     low   close
4999  01/26/1998  1.1090  1.1196  1.0963  1.0991
4998  01/27/1998  1.0991  1.1055  1.0985  1.1022
4997  01/28/1998  1.1021  1.1021  1.0877  1.0878
4996  01/29/1998  1.0870  1.0927  1.0785  1.0799
4995  01/30/1998  1.0792  1.0865  1.0771  1.0790
...          ...     ...     ...     ...     ...
4     03/21/2017  1.0740  1.0822  1.0720  1.0811
3     03/22/2017  1.0810  1.0827  1.0776  1.0797
2     03/23/2017  1.0797  1.0807  1.0769  1.0783
1     03/24/2017  1.0784  1.0820  1.0761  1.0799
0     03/27/2017  1.0797  1.0905  1.0795  1.0865

[5000 rows x 5 columns]

In [5]:
print(windower.create_window_indexes(10,5))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [6]:
import Create_labels as cl

In [7]:
labels = cl.multi_distance_labele_creator(rawdata,0.01,0.1,4)

lims = 
 [0.01 0.04 0.07 0.1 ]


In [21]:
clab = pd.DataFrame(labels.copy())
clab.index=rawdata.index
clab

0    1    2    3    4    5    6    7
4999  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
4998  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
4997  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
4996  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
4995  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5000 rows x 8 columns]

In [16]:
rawdata

date    open    high     low   close
4999  01/26/1998  1.1090  1.1196  1.0963  1.0991
4998  01/27/1998  1.0991  1.1055  1.0985  1.1022
4997  01/28/1998  1.1021  1.1021  1.0877  1.0878
4996  01/29/1998  1.0870  1.0927  1.0785  1.0799
4995  01/30/1998  1.0792  1.0865  1.0771  1.0790
...          ...     ...     ...     ...     ...
4     03/21/2017  1.0740  1.0822  1.0720  1.0811
3     03/22/2017  1.0810  1.0827  1.0776  1.0797
2     03/23/2017  1.0797  1.0807  1.0769  1.0783
1     03/24/2017  1.0784  1.0820  1.0761  1.0799
0     03/27/2017  1.0797  1.0905  1.0795  1.0865

[5000 rows x 5 columns]

In [26]:
t[0]=False
t

[False, True, True, True, True]

In [27]:
t.index(True)

1